language: python
dist: trusty
python: "3.7.4"
env:
  global:
    - BOTO_CONFIG=/dev/null
    - PIPENV_IGNORE_VIRTUALENVS=1
  matrix:
    - COMMAND="pytest --cov-report term-missing --cov=pakkr --cov-fail-under=100"
branches:
  only: [master]
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run $COMMAND
notifications:
webhooks:
